### ISSUE TITLE
wifi bridge

### ISSUE THREAD

**Issue by bam80** [Raizo62/vwifi#13]
Hello,
is there any possibility to "bridge" virtual WiFi network with the real one?
I would like to connect the virtual WiFi adapter on Guest with real AP via real WiFi adapter on Host.

**Comment by Raizo62** [comment]
Hi

The virtual wifi, which uses a limited wifi interface provided by the linux kernel, can only communicate with other same virtual wifis.
So I think it's not possible. But you can try.
