### ISSUE TITLE
OpenWRT X86_64 porting

### ISSUE THREAD

**Issue by nickbash11** [Raizo62/vwifi#2]
I get an unsolvable situation during attempt to compile vwifi on [OpenWRT SDK.](https://downloads.openwrt.org/releases/19.07.4/targets/x86/64/openwrt-sdk-19.07.4-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz)
So yes, I've create a Makefile, and you can see it in my [git repository ](https://github.com/nickbash11/gitpkg/tree/master/vwifi)
But it has missing libraries, which do not present in openwrt packages:

> Package vwifi is missing dependencies for the following libraries:
> libc.so.6
> libm.so.6
> libpthread.so.0

[vwifi.log](https://github.com/Raizo62/vwifi/files/5225033/vwifi.log)
But those are presented in SDK directory openwrt-sdk-19.07.4-x86-64_gcc-7.5.0_musl.Linux-x86_64/staging_dir/host/lib/

Could you help me to solve this issue?

**Comment by Raizo62** [comment]
Hi

I works on a branch to compile vwifi on OpenWRT. It works. I will push the branch (as soon as possible).

For libnl, i have cross compiled the files of Debian. I will put the method on the wiki.
Or have you a better idea ?

**Comment by nickbash11** [comment]
No, I have no idea, I've just tried to run it with static method by copying files to OpenWRT virtual machine, but it persistently does not find the libstdc++.so.6 :( 
https://paste.ubuntu.com/p/hVN4jqW9jH/

**Comment by nickbash11** [comment]
Ok, it worked when I put all missing libraries to the dir with strange path "/###" , if it matters.

![Screenshot_2020-09-15_17-33-09](https://user-images.githubusercontent.com/3481744/93224379-b5b71700-f779-11ea-8a4b-9df4ee1c2ad1.png)

I will be waiting for your branch! Thanks in advance!

**Comment by Raizo62** [comment]
**vwifi-server** is useless on OpenWRT. You must run **vwifi-guest**

**Comment by Raizo62** [comment]
the branch "openwrt" is push

**Comment by nickbash11** [comment]
> **vwifi-server** is useless on OpenWRT. You must run **vwifi-guest**

Why? I am going to connect two-more OpenWRT nodes in virtualbox, do I have to start vwifi-server on the host system anyway?

**Comment by Raizo62** [comment]
You are right. You can start **vwifi-server** on OpenWRT, but you can also start it on other Linux.
But you must start **vwifi-guest** on OpenWRT.

**Comment by nickbash11** [comment]
It is really weird, I had to add a directory with strange [name "###"](https://github.com/nickbash11/gitpkg/tree/master/vwifi/files/%23%23%23) and put all links to libs, otherwise it does not find anything. Something wrong with toolchain maybe...

**Comment by nickbash11** [comment]
> You are right. You can start **vwifi-server** on OpenWRT, but you can also start it on other Linux.
> But you must start **vwifi-guest** on OpenWRT.

Ok, I start vwifi-server on one node, and start vwifi-guest on the other node? The last one will be connect to vwifi-server (via IP I think), am I right?

**Comment by Raizo62** [comment]
No. **vwifi-server** is like a hub/switch. 
**vwifi-guest** must be started on each OpenWRT. The 2 **vwifi-guest** must connect to **vwifi-server** via IP (I don't know how to start VHost on OpenWRT)

**Comment by Raizo62** [comment]
The wiki to compile vwifi on OpenWRT  : https://github.com/Raizo62/vwifi/wiki/Install-on-OpenWRT
It's not over yet, but it can help you

**Comment by nickbash11** [comment]
> No. **vwifi-server** is like a hub/switch.
> **vwifi-guest** must be started on each OpenWRT. The 2 **vwifi-guest** must connect to **vwifi-server** via IP (I don't know how to start VHost on OpenWRT)

I understood from this point.

**Comment by nickbash11** [comment]
![Screenshot_2020-09-15_21-19-28](https://user-images.githubusercontent.com/3481744/93248945-3f2a1180-f799-11ea-8962-467525947ec8.png)
oops! :(

**Comment by Raizo62** [comment]
You have use the wiki to build vwifi-guest ?

**Comment by nickbash11** [comment]
> You have use the wiki to build vwifi-guest ?

Wow, Sorry, I did not get it right away. I will try it for tomorrow

**Comment by nickbash11** [comment]
Tried to compile it on OpenWRT host and got an error:
[vwifi_openwrt_compile.log](https://github.com/Raizo62/vwifi/files/5230237/vwifi_openwrt_compile.log)

I do not understand why I need to compile libnl if it has already presented in openwrt repository?

> PKG_NAME:=libnl
PKG_VERSION:=3.4.0
PKG_RELEASE:=2

>PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/thom311/libnl/releases/download/libnl3_4_0
PKG_HASH:=b7287637ae71c6db6f89e1422c995f0407ff2fe50cecd61a312b6a9b0921f5bf
PKG_LICENSE:=LGPL-2.1

**Comment by nickbash11** [comment]
What do I need to do after libnl built? 
vwifi did not compile on OpenWRT because include files (netlink) does not exist.

**Comment by nickbash11** [comment]
Ok, it was very struggled...
After this point https://github.com/Raizo62/vwifi/wiki/Install-on-OpenWRT#compilation-of-libnl-for-openwrt you have to copy includes and libraries to OpenWRT /usr/lib and then create libpthread.a

> libnl-3.a                                                                                                                                                                                                    
libnl-3.la                                                                                                                                                                                                    
libnl-cli-3.a                                                                                                                                                                                                
libnl-cli-3.la                                                                                                                                                                                                
libnl-genl-3.a                                                                                                                                                                                                   
libnl-genl-3.la                                                                                                                                                                                               
libnl-idiag-3.a                                                                                                                                                                                                
libnl-idiag-3.la                                                                                                                                                                                                
libnl-nf-3.a                                                                                                                                                                                                    
libnl-nf-3.la                                                                                                                                                                                                   
libnl-route-3.a                                                                                                                                                                                              
libnl-route-3.la                                                                                                                                                                                              
libnl-xfrm-3.a                                                                                                                                                                                                
libnl-xfrm-3.la                                                                                                                                                                                                

after that I could only execute **make** and it has assembled 

![Screenshot_2020-09-16_12-29-56](https://user-images.githubusercontent.com/3481744/93319805-fe71dd00-f818-11ea-99b4-af4330060428.png)

**Comment by nickbash11** [comment]
Now I am going to do some tests and then the question how to create a package ipk through SDK will still remain for me, though I can make it as a static precompiled binaries...

**Comment by nickbash11** [comment]
Something wrong, I connected 3 machines, two are debian and one is openwrt (virtualbox)

```
$ ./vwifi-ctrl show
PacketLoss : Disable
Host : Connected
----------------
[15114](10,10,10)
[108736](10,10,10)
[113600](10,10,10)
```
Two of them are in 802.11s (mesh point) mode, and one is the monitor. And packets do not travel between them :(
What can I do?

**Comment by nickbash11** [comment]
Furthermore, if I connect two OpenWRT virtualbox then I get errors:
![Screenshot_2020-09-16_16-43-08](https://user-images.githubusercontent.com/3481744/93345730-d47de200-f83b-11ea-9be2-35edd3005fd0.png)

**Comment by Raizo62** [comment]
I have see strange behavior in OpenWRT, that, now, i can't explain.
In my tests, OpenWRT was the AP and a Debian was a client.  Often, OpenWRT deleted a wlan interface as soon as i configured it.
I haved not this case if OpenWRT was the client and the Debian the AP. After this success, I was able to configure OpenWRT as an AP.
Perhaps OpenWRT must be reboot after the install of kmod-mac80211-hwsim

**Comment by nickbash11** [comment]
I would be happy if it worked at least on debian. Try to test again with a fresh brain, might be I did something wrong

**Comment by nickbash11** [comment]
I confirm, it works between two debian nodes! I use 802.11s (MESH) protocol, nodes see each other and can ping. But OpenWRT connects shortly and even displays in station dump table, but every time it reconnects with an error message:

**Error - recieved no frame data in message**

**Comment by Raizo62** [comment]
I have updated the wiki.

Have you tested to use the Debian as AP and OpenWRT as Client. When it works, you transform OpenWRT like AP ?

I have success to use OpenWRT as AP with WPA2/WPAEntreprise

**Comment by nickbash11** [comment]
> I have updated the wiki.

I did

>Have you tested to use the Debian as AP and OpenWRT as Client. When it works, you transform OpenWRT like AP ?

I have setup an AP on OpenWRT:

```
root@OpenWrt:~# iw dev
phy#1
	Interface wlan1
		ifindex 5
		wdev 0x100000001
		addr 02:00:00:00:01:00
		type managed
		txpower 0.00 dBm
phy#0
	Interface wlan0
		ifindex 8
		wdev 0x2
		addr 00:00:00:ff:ff:ff
		ssid OpenWrt
		type AP
		channel 6 (2437 MHz), width: 20 MHz (no HT), center1: 2437 MHz
		txpower 20.00 dBm
```



 and connected  it to the vwifi-server, it's ok when the "radio broadcast" keeps silence, but when I do something like "**iwlist wlan0 scan**" on the other side, (e.g. generate any packets) OpenWRT begins to reconnect with **Error - recieved no frame data in message**

**Comment by nickbash11** [comment]
I even can see it through airodump-ng wlan0

![Screenshot_2020-09-17_20-45-31](https://user-images.githubusercontent.com/3481744/93507766-d53f7280-f926-11ea-82cb-7b30f926de92.png)

**Comment by Raizo62** [comment]
Where is your **vwifi-server** ?
The TCP communications between the vwifi-guest and vwifi-server are stables ?

**Comment by nickbash11** [comment]
> Where is your **vwifi-server** ?

There is where the virtualbox machine

> The TCP communications between the vwifi-guest and vwifi-server are stables ?

Certainly, I was connected to it via ssh at that moment.

Debian works fine with the same configuration.

**Comment by nickbash11** [comment]
Could I give you the Virtualbox image with openwrt? You would see how it is

**Comment by Raizo62** [comment]
Yes, you can.

**Comment by nickbash11** [comment]
https://www.filedropper.com/openwrt-19 It is the first file hosting which I found in google.

There are two network cards attached as bridges in that machine (for eth0 and eth1 accordingly).

**Comment by Raizo62** [comment]
Sorry : 

- what is the password of root ?
- when i go on http://192.168.1.1 , i have the web explorer of files and not the web interface

**Comment by nickbash11** [comment]
>what is the password of root ?

root password is "**password**" :)
I usually use it through virtualbox screen, there you can change the password.

>when i go on http://192.168.1.1 , i have the web explorer of files and not the web interface

Hmm, I do not use web interface as a rule, just do not know it works or not.

**Comment by nickbash11** [comment]
You'll find all need files in /root directory

**Comment by Raizo62** [comment]
Sorry, i don't know how to configure Wifi on OpenWRT without web interface, then I can't test.

The mine is OpenWrt 19.07.3, r11063-85e04e9f46. Yours is 19.07.4. I don't know if you changed anything on your version of OpenWRT ; or perhaps they have modify something, But files are missing for the web page

**Comment by nickbash11** [comment]
>Sorry, i don't know how to configure Wifi on OpenWRT without web interface, then I can't test.

There is already configured as open with name Openwrt

>The mine is OpenWrt 19.07.3, r11063-85e04e9f46. Yours is 19.07.4.

Ok, I'll try exact 19.07.03  r11063-85e04e9f46 and then write about results.

**Comment by nickbash11** [comment]
This time I was strictly followed the rules from wiki (with version), and got the same behavior when I did scanning from the other machine.
This machine has web interface and root password is **password** , all files are in the root directory as well.

http://www.filedropper.com/openwrt-19073

**Comment by nickbash11** [comment]
![Screenshot_2020-09-19_17-51-55](https://user-images.githubusercontent.com/3481744/93670044-d98f9b00-faa0-11ea-936c-db25679844d5.png)

**Comment by Raizo62** [comment]
I have tested your VM. OpenWRT was the Open AP and a Debian was the Client. The Debian got his IP by DHCP.

Where is your **vwifi-server** ?

(With my test, the Debian and the **vwifi-server** use the beta branch. But, I guess it doesn't change anything)

**Comment by nickbash11** [comment]
Hmmm, I've tried vwifi server on two different PCs, one is my laptop and the other is PC with Kali linux, there are where virtual machines running.

So, tomorrow I will try to run vwifi-server on virtualbox with debian. By the way, what debian version do you use?

**Comment by Raizo62** [comment]
Kali Linux is like Debian. VWifi works on it.

With my test, OpenWRT and Debian were VM, and vwifi-server was on the hypervisor (Debian Buster)

**Comment by Raizo62** [comment]
Are you sure that your IP network of Wifi is not in conflict with the IP network of vwifi programs ?

**Comment by Raizo62** [comment]
For vwifi programs on Debian like, you should perhaps use the beta branch

**Comment by nickbash11** [comment]
> For vwifi programs on Debian like, you should perhaps use the beta branch

Yes, I did it and it works properly

**Comment by Raizo62** [comment]
> 
> 
> > For vwifi programs on Debian like, you should perhaps use the beta branch
> 
> Yes, I did it and it works properly

With OpenWRT ? or only between Debian like ?

**Comment by nickbash11** [comment]
> With OpenWRT ? or only between Debian like ?

I've tested ping with OpenWRT as two mesh nodes (IEEE802.11s), and OpenWRT as an AP with debian as a client. Both case show me that icmp packets more than 830 and 854 bytes (mesh and AP) do not pass through virtual wifi connection.

![Screenshot_2020-09-20_14-21-23](https://user-images.githubusercontent.com/3481744/93710095-9ee33c80-fb4c-11ea-871b-14f6d592779a.png)

One of the host starts to reconnect every time when the packet does not fit in

You can try it with command: **ping -s 1000 ap_openwrt_host**

I have not tried it between two debian-like OS so do not know

**Comment by Raizo62** [comment]
I have not tested but, in src/types.h , try to change "typedef unsigned short TMinimalSize;" in "typedef unsigned int TMinimalSize;"

**Comment by nickbash11** [comment]
It does not help. Perhaps it is the matter for the other issue. Was it tested ever?

**Comment by Raizo62** [comment]
> You can try it with command: ping -s 1000 ap_openwrt_host

I can reproduce the deconnection. I will see what i can do.

**Comment by Raizo62** [comment]
To test : 

- Forget all old modifications
- Use the OpenWRT branch with all
- And in vwifi-server.cc, in the method "ForwardData", increase the array "char buffer[1024]" to "char buffer[2048]"

**Comment by Raizo62** [comment]
No, it is not enough. Sorry

**Comment by Raizo62** [comment]
Can you test this branch : bug_big_ping ?

**Comment by nickbash11** [comment]
> Can you test this branch : bug_big_ping ?

I will test it as soon as I can. Do I have to use that branch for OpenWRT and Debian hosts?

**Comment by Raizo62** [comment]
> Do I have to use that branch for OpenWRT and Debian hosts?

Yes. I hope the code is compatible. The differences are not in the functions.

**Comment by nickbash11** [comment]
I've tested. It keeps stable up to 1200 bytes, over that it starts to reconnect and even falls to segmentation fault.
![Screenshot_2020-09-22_12-42-13](https://user-images.githubusercontent.com/3481744/93866987-14781580-fcd1-11ea-9c5c-c5ec9f0922fb.png)

**Comment by Raizo62** [comment]
After debug, to "solve", i have increase an array from 1024 to 2048.
I have tested with `ping -c 5 -s 3000 10.0.0.1` between 2 Debians without error.

I am surprize that you crash with 1200 bytes. I can use a dynamic array, but perhaps there is an other bug

**Comment by Raizo62** [comment]
Are you sure to use the last version on each VM / Server ?

**Comment by nickbash11** [comment]
> Are you sure to use the last version on each VM / Server ?

I used Openwrt as an AP and Debian as a client.

**Comment by nickbash11** [comment]
I precisely checked out to the branch **bug_big_ping** and then copied it to OpenWRT and Debian VM

**Comment by nickbash11** [comment]
Can you add some function to control the commit version of the binary files? something like:

```
# vwifi-guest --version
commit 2a8216e98162d1abf04bf315cbc51754c3ccc9d8
```

It can help to debug in the future to understand what exactly version we use on the host.

**Comment by nickbash11** [comment]
I've convinced that two debian VM get the same result in AP and MESH modes.

**Comment by Raizo62** [comment]
I try a dynamic buffer.

In the meantime, you can try : 

- For the segmentation fault : In ckernelwifi.cc , move "char Buffer[2048];"  (line 34) in the top of "void CKernelWifi::recv_from_server()"
- No frame data : In ckernelwifi.cc and vwifi-server.cc, increase the size of "Buffer"

Could you give me your commands to config the OpenWRT ?

**Comment by nickbash11** [comment]
>     * For the segmentation fault : In ckernelwifi.cc , move "char Buffer[2048];"  (line 34) in the top of "void CKernelWifi::recv_from_server()"

There are buffers already on top

>     * No frame data : In ckernelwifi.cc and vwifi-server.cc, increase the size of "Buffer"

Increased buffers up to 4096 have no effect, it has stuck on 1270 bytes max.

>    Could you give me your commands to config the OpenWRT ?

I configure it via editing config files /etc/config/network and /etc/config/wireless ,not via uci or luci
You can see it in that VM http://www.filedropper.com/openwrt-19073 which I've already represented

**Comment by Raizo62** [comment]
> There are buffers already on top

in ckernelwifi.cc , move "char Buffer[2048];" (line 34) to line 513 (top of "void CKernelWifi::recv_from_server()")

**Comment by nickbash11** [comment]
> in ckernelwifi.cc , move "char Buffer[2048];" (line 34) to line 513 (top of "void CKernelWifi::recv_from_server()")

Segfaults disappeared. What I could reach is about 1400 bytes with 50% loss.

**Comment by Raizo62** [comment]
Could you test again the branch **bug_big_ping** ?

**Comment by nickbash11** [comment]
The compilation ends with error

[vwifi_compile_erorr.txt](https://github.com/Raizo62/vwifi/files/5281813/vwifi_compile_erorr.txt)

**Comment by Raizo62** [comment]
* `undefined reference to`

You forgot to update the path of libnl in the Makefile

* `is deprecated`

Is it a new warning ? have you updated your builder g++ ? what is his version ?

**Comment by nickbash11** [comment]
>You forgot to update the path of libnl in the Makefile

```
NETLINK_FLAGS = -I/usr/include/libnl3
NETLINK_LIBS = -lnl-genl-3 -lnl-3
```
I've just checked out to bug_big_ping as always

> Is it a new warning ? have you updated your builder g++ ? what is his version ?

```
root@builds:~# g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@builds:~# cat /etc/debian_version 
10.5
```
Pure Debian and Kali Linux both systems have the same error.

**Comment by nickbash11** [comment]
```
# git branch -a
* bug_big_ping
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/beta
  remotes/origin/bug_big_ping
  remotes/origin/bug_dhcp
  remotes/origin/dhcp
  remotes/origin/for_liveraizo_v11.20.02.23p
  remotes/origin/for_liveraizo_v11.20.04.27p
  remotes/origin/for_liveraizo_v11.20.06.28p
  remotes/origin/for_liveraizo_v11.20.09.14p
  remotes/origin/master
  remotes/origin/openwrt
  remotes/origin/readme
```

**Comment by Raizo62** [comment]
> > 
> > You forgot to update the path of libnl in the Makefile
> 
> ```
> NETLINK_FLAGS = -I/usr/include/libnl3
> NETLINK_LIBS = -lnl-genl-3 -lnl-3
> ```

g++ doesn't found library files (.a or .so) of libnl

On Openwrt, edit the file "Makefile" to modify the values of :
    NETLINK_LIBS = **-L/root/libnl/libs** -lnl-genl-3 -lnl-3

> 
>> 
> > Is it a new warning ? have you updated your builder g++ ? what is his version ?
> 
> ```
> root@builds:~# g++ --version
> g++ (Debian 8.3.0-6) 8.3.0
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> root@builds:~# cat /etc/debian_version 
> 10.5
> ```
> 
> Pure Debian and Kali Linux both systems have the same error.

Thank you. I can reproduce to remove the warnings.
But it is warnings. It does not matter

**Comment by nickbash11** [comment]
> g++ doesn't found library files (.a or .so) of libnl
> 
> On Openwrt, edit the file "Makefile" to modify the values of :
> NETLINK_LIBS = **-L/root/libnl/libs** -lnl-genl-3 -lnl-3

I catch the same error on Debian and OpenWrt, I always change makefile according to the wiki for openwrt.

Ok, I've just built master branch without any problems with the same environment on the debian, but the branch bug_big_ping can't

**Comment by nickbash11** [comment]
I added $(NETLINK_LIBS) to 93 string of Makefile and it built

**Comment by Raizo62** [comment]
Yes. You are right. I had remove accidentally this variable from Makefile.
I have updated the branch

**Comment by nickbash11** [comment]
it seems to work

**Comment by nickbash11** [comment]
**opkg update** was success through vwifi and 802.11s ! That was what I needed

**Comment by Raizo62** [comment]
Thank you for your help :-)
