### ISSUE TITLE
Can't see the traffic generated on the same machine on another interface

### ISSUE THREAD

**Issue by r4ulcl** [Raizo62/vwifi#5]
Is there any option for a VM to see the traffic generated on the same machine on another interface?

My configuration is as follows:
    - VM attacker (server)
    - VM AP (client)

When the attacker raises a Rogue AP from one of the interfaces, from the rest of the same machine does not appear that traffic. it only appears if the server is not raised. 

I have tried to monitor the traffic with airodump-ng from the AP VM but I can't see the traffic from the rest of the interfaces either, only the traffic from the attacker VM. Each one can see the traffic of the rest but not their own, not even in spy mode. 

Thank you very much, I love the repo.

**Comment by Raizo62** [comment]
Hi

Sorry, i don't understand : 
- On the VM attacker, you have the Server AND a Client, or only the Server ? (On each "Wifi" VM, you must have at least one Client)
- Do you use VHost or TCP ? (I assume TCP)

**Comment by Raizo62** [comment]
* On AP : 
```
ifconfig wlan0 down
iwconfig wlan0 mode Monitor
ifconfig wlan0 up

create_ap wlan0 wlan0 MyAccessPoint MyPassPhrase
```
* On an other tab of AP
`tcpdump -n -e -i wlan0`

Then i can see the broadcast of BSSID

(But perhaps that i don't understand your question)

**Comment by r4ulcl** [comment]
I am using TCP, one VM has the server and a client, and the other has only a client. The problem is when trying to see the wlan0 AP from wlan1 in the same machine. From the other VM it can be seen without problems. And if you don't use vwifi using only mac80211_hwsim locally also works. 

Without vwifi (only mac80211_hwsim local):
![image](https://user-images.githubusercontent.com/25440046/179201008-dbeba23b-d5e6-4202-8a5a-d11f22a66589.png)

Using vwifi:
![image](https://user-images.githubusercontent.com/25440046/179200930-56c56acf-c546-4585-90e5-91d2c323dc40.png)

And using vwifi from the other VM (server+client):
![image](https://user-images.githubusercontent.com/25440046/179200803-f15a0033-800c-4132-bcb2-ee902de38dd5.png)

**Comment by Raizo62** [comment]
Could you do **all** your tests with this branch [send_to_interfaces_on_same_VM](https://github.com/Raizo62/vwifi/tree/send_to_interfaces_on_same_VM) ?

Thank you

**Comment by r4ulcl** [comment]
OK, now it seems to work fine. I have created an AP on wlan0 and I can see the traffic from wlan1 (airodump-ng wlan1mon -c1). 

![image](https://user-images.githubusercontent.com/25440046/179813346-ab79b300-fef9-42b3-9d27-586c29f6d1c2.png)

I am going to do more tests in my lab, but everything seems to be working perfectly. Thank you very much. 
I close the issue, if it is possible to include it in the main branch great, meanwhile I use this branch. 

Thank you very much for the help and for the project.
